version: '3'

services:
    app:
        build: ./docker/php-fpm
        volumes:
            - ./src:/var/www/html
        depends_on:
            - db
    web:
        build: ./docker/nginx
        tty: true
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - app
            - db
    db:
        build: ./docker/mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: YV1dI#h5eDWgjoyM
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: pass